In [1]:
import numpy as np
from scipy import signal
from skimage.measure import block_reduce

In [15]:
# Golden model for 2D convolution
# Used to compare with the hardware implementation

k = 3
n = 5

kernel = np.arange(0, k*k, 1).reshape((k, k))
activation_map = np.arange(0, n*n, 1).reshape((n, n))

conv1 = signal.correlate2d(activation_map, kernel, mode='valid')
conv2 = signal.convolve2d(activation_map, kernel, mode='valid')

print("Kernel:")
print(kernel)
print("Activation Map:")
print(activation_map)
print("Convolution Result:")
print(conv1)

Kernel:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Activation Map:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Convolution Result:
[[312 348 384]
 [492 528 564]
 [672 708 744]]


In [21]:
n = 8

input_map = np.arange(0, n*n, 1).reshape((n, n))

max_pool = block_reduce(input_map, (2, 2), np.max)

print("Input Map:")
print(input_map)
print("Max Pooling Result:")
print(max_pool)

Input Map:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
Max Pooling Result:
[[ 9 11 13 15]
 [25 27 29 31]
 [41 43 45 47]
 [57 59 61 63]]


In [2]:
vector = np.array([0, 1, 2, 3])

# Define the 4x3 matrix
# The matrix is a 2D array of shape (4, 3)
# It contains numbers from 0 to 11, filled row by row
matrix = np.arange(12).reshape(4, 3)

result = np.dot(vector, matrix)

print(result)

[42 48 54]
