In [2]:
import numpy as np
from scipy import signal

In [9]:
# Golden model for 2D convolution
# Used to compare with the hardware implementation

k = 3
n = 4

kernel = np.arange(0, k*k, 1).reshape((k, k))
activation_map = np.arange(0, n*n, 1).reshape((n, n))

conv1 = signal.correlate2d(activation_map, kernel, mode='valid')
conv2 = signal.convolve2d(activation_map, kernel, mode='valid')

print("Kernel:")
print(kernel)
print("Activation Map:")
print(activation_map)
print("Convolution Result:")
print(conv1)

Kernel:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Activation Map:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Convolution Result:
[[258 294]
 [402 438]]
